### ISSUE TITLE
Izrada klase za financijska izvješća

### ISSUE THREAD

**Issue by Alpfonso** [Alpfonso/Evidencija-i-administracija-radnika#19]
Financijska izvješća koristi Financijski sektor

Potrebne funkcionalnosti izvješća
- [x] Prihodi i rashodi
- [x] Odabir perioda (npr. 01.01.2001. - 02.02.2002.)
- [x] Odabir format izvješća (pdf ili xlsx)
- [x] Dokument mora biti prilagođen ispisu

**Comment by apolatan11** [comment]
Dodane potrebne varijable i inicijalne metode u klasu Financijska_izvjesca. Nasljeđuje se klasa Alati.
