### ISSUE TITLE
Izrada osnovne klase Radnik

### ISSUE THREAD

**Issue by Alpfonso** [Alpfonso/Evidencija-i-administracija-radnika#26]
Superklasa radnik. Sadrži sve potrebne podatke o radnicima.

Potrebni atributi

- [x] Id
- [x] Ime
- [x] Prezime
- [x] Datum rođenja
- [x] Grad stanovanja
- [x] Ulica i broj
- [x] email
- [x] OIB
- [x] Telefon
- [x] Obrazovanje
- [x] Razina ovlasti
- [x] Radno vrijeme start/end
- [x] Slobodni dani

**Comment by apolatan11** [comment]
Dodane varijable u osnovnu klasu radnik.
Dodan konstruktor za inicijalizaciju varijabli.
