### ISSUE TITLE
Izrada podklase Administracija

### ISSUE THREAD

**Issue by Alpfonso** [Alpfonso/Evidencija-i-administracija-radnika#36]
Podklasa klase Administracija

ovisi o #26

Potrebne funkcionalnosti

- [x] Postavljanje Nadređenih
- [x] Pregled Anketa
- [x] Proslijeđivanje Financijskih izvješća

**Comment by apolatan11** [comment]
Dodani potrebni getteri unutar klase Administracija, podložno promjenama
