### ISSUE TITLE
Izrada podklase HR

### ISSUE THREAD

**Issue by Alpfonso** [Alpfonso/Evidencija-i-administracija-radnika#38]
Podklasa klase Administracija

ovisi o #36 

Potrebne mogućnosti:

- [x] Provođenje anketa
- [x] Ispis anketa
- [x] Prosljeđivanje anketa

**Comment by apolatan11** [comment]
Dodane potrebne metode i getteri, potrebno ispisivati rezultate anketa, no to će se implementirati nakon što GUI postane funkcionalan
