### ISSUE TITLE
Izrada podklase Financijski sektor

### ISSUE THREAD

**Issue by Alpfonso** [Alpfonso/Evidencija-i-administracija-radnika#40]
Podklasa klase Administracija

ovisi #36 

Potrebne mogućnosti

- [x] Pregled financijskog izvješća
- [x] Pregled izvješća u određenom razdoblju

**Comment by apolatan11** [comment]
Dodane metode potrebne za izvršavanje željenih funkcija, član financijskog sektora ima i mogućnost dobavljanja po periodu
